# It's important that the version of serverless is larger than 1.4 as this is the version that
# introduced correctly the `async: true` invocationType for API Gateway events.
frameworkVersion: '>=1.4.0'

service: in-stock-checker

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  secrets:
    # Secrets from SSM are loaded here
  webpack: # used for serverless framework to bundle and send to aws
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
  pruneCount:
    dev: 2
    production: 3
  prune:
    automatic: true
    number: ${self:custom.pruneCount.${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  environment:
    PLANT_URL: 'https://www.logees.com/variegated-mexican-breadfruit-monstera-deliciosa-variegata.html'
    PLANT_IN_STOCK_TOPIC: !Ref PlantInStockTopic

functions:
  checkPlantInStock:
    handler: functions/check-plant-in-stock.handler
    events:
      - schedule:
          rate: rate(2 minutes)

resources:
  Resources:
    PlantInStockTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        DisplayName: Plant is in stock!
        TopicName: plantInStock-${self:custom.stage}
  Outputs:
    PlantInStockTopicArn:
      Description: The ARN for the PlantInStockTopic
      Value:
        Ref: PlantInStockTopic
      Export:
        Name: event:${self:custom.stage}:plantInStock
